/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ComicSansMS12_width_h_
#define _ComicSansMS12_width_h_
//---------------------------------------------------------------------------------
extern const unsigned char ComicSansMS12_width[];
extern const int ComicSansMS12_width_size;
//---------------------------------------------------------------------------------
#endif //_ComicSansMS12.width_h_
//---------------------------------------------------------------------------------
