/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ComicSansMS10_width_h_
#define _ComicSansMS10_width_h_
//---------------------------------------------------------------------------------
extern const unsigned char ComicSansMS10_width[];
extern const int ComicSansMS10_width_size;
//---------------------------------------------------------------------------------
#endif //_ComicSansMS10.width_h_
//---------------------------------------------------------------------------------
