/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ComicSansMS10_h_
#define _ComicSansMS10_h_
//---------------------------------------------------------------------------------
extern const unsigned char ComicSansMS10[];
extern const int ComicSansMS10_size;
//---------------------------------------------------------------------------------
#endif //_ComicSansMS10_h_
//---------------------------------------------------------------------------------
