/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ComicSansMS12_h_
#define _ComicSansMS12_h_
//---------------------------------------------------------------------------------
extern const unsigned char ComicSansMS12[];
extern const int ComicSansMS12_size;
//---------------------------------------------------------------------------------
#endif //_ComicSansMS12_h_
//---------------------------------------------------------------------------------
