/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _ComicSansMS10.height_h_
#define _ComicSansMS10.height_h_
//---------------------------------------------------------------------------------
extern const unsigned char ComicSansMS10.height[];
extern const int ComicSansMS10.height_size;
//---------------------------------------------------------------------------------
#endif //_ComicSansMS10.height_h_
//---------------------------------------------------------------------------------
