/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _font6x8_width_h_
#define _font6x8_width_h_
//---------------------------------------------------------------------------------
extern const unsigned char font6x8_width[];
extern const int font6x8_width_size;
//---------------------------------------------------------------------------------
#endif //_font6x8_width_h_
//---------------------------------------------------------------------------------
