/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _LucidaConsole10_width_h_
#define _LucidaConsole10_width_h_
//---------------------------------------------------------------------------------
extern const unsigned char LucidaConsole10_width[];
extern const int LucidaConsole10_width_size;
//---------------------------------------------------------------------------------
#endif //_LucidaConsole10.width_h_
//---------------------------------------------------------------------------------
