/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _LucidaConsole10_h_
#define _LucidaConsole10_h_
//---------------------------------------------------------------------------------
extern const unsigned char LucidaConsole10[];
extern const int LucidaConsole10_size;
//---------------------------------------------------------------------------------
#endif //_LucidaConsole10_h_
//---------------------------------------------------------------------------------
