/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Noritake5x5.width_h_
#define _Noritake5x5.width_h_
//---------------------------------------------------------------------------------
extern const unsigned char Noritake5x5.width[];
extern const int Noritake5x5.width_size;
//---------------------------------------------------------------------------------
#endif //_Noritake5x5.width_h_
//---------------------------------------------------------------------------------
