/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _Noritake5x5_h_
#define _Noritake5x5_h_
//---------------------------------------------------------------------------------
extern const unsigned char Noritake5x5[];
extern const int Noritake5x5_size;
//---------------------------------------------------------------------------------
#endif //_Noritake5x5_h_
//---------------------------------------------------------------------------------
